apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: budget-app
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  project: default
  source:
    repoURL: 'https://github.com/Ritik200w/Budget-App.git'
    path: manifests/  # Assuming your manifests are in the "manifests/" directory
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
